config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followed', as: 'follows'
    get 'followers' => 'relationships#follower', as: 'followers'
    get 'leave', :on => :collection
  end

  resources :posts do
  	resource :favorites, only: [:create, :destroy]
    post "bookmarks" => 'bookmarks#create'
    delete '/bookmarks' => 'bookmarks#destroy'
  end

  root to: 'home#top'
  get 'home/about' => 'home#about'
  get 'home/index' => 'home#index'
  get 'users/leave' => 'users#leave', as: 'leave'
  get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post

  validates :name, presence: true, length: {minimum:2,maximum:12}

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.where.not(id: current_user.id).page(params[:page]).per(15).order(created_at: :desc)
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to home_index_path(@user.id)
		else
		  render :edit
		end
	end

	def leave
	end

	def destroy
	   @user = User.find(params[:id])
	   @user.destroy
	   flash[:success] = 'ユーザーを削除しました。'
	   redirect_to :root
	end

	private
  def user_params
        params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def screen_user
      unless params[:id].to_i == current_user.id
        redirect_to user_path(current_user)
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.erb
<div class="col-sm-3">
  <h1>About Me</h1>
  <div class="profile_image">
    <%= attachment_image_tag user, :profile_image, :fill, 150, 150, format: 'jpeg', class: "img-circle center-block profile-img", fallback: "no_image.jpg", size:'120x135' %>
  </div>
  <table class="table">
    <tbody>
      <tr>
        <td>name</td>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <td>introduction</td>
        <td><%= user.introduction %></td>
      </tr>
      <tr>
        <td>follows :　</td>
        <td><%= link_to user.follower.count, user_follows_path(user), class: "btn btn-default" %></td>
      </tr>
      <tr>
        <td>followers : </td>
        <td><%= link_to user.followed.count, user_followers_path(user), class: "btn btn-default" %></td>
      </tr>
    </tbody>
  </table>
  <div class= "actions row">
    <%= link_to "My page", user_path(user), class: "btn btn-primary btn-block" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-2">
			<h1>Edit page</h1>
		</div>
	</div>
	   <%= form_for(@user, url: user_path) do |f| %>
	<div class="row">
		<div class="col-sm-8 col-md-offset-2">
			<% if @user.errors.any? %>
			<div id="error_explanation" class="alert alert-danger">
				<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
				<ul>
					<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
			<p>ファイル選択 <%= f.attachment_field :profile_image %></p>
		</div>
	</div>
	<div class="row">
		<div class="show-table col-sm-8 col-sm-offset-2">
			<table class="table">
		  <tr class="show-tr2">
			<th>Your name</th>
			<th><%= f.text_field :name %></th>
		  </tr>
		  <tr class="show-tr2">
			<th>Introduction</th>
			<th><%= f.text_area :introduction %></th>
		  </tr>
		    </table>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-1 col-sm-offset-8">
			<p><%= f.submit 'Save', class: "btn btn-primary"%></p>
			<% end %>
		</div>
		<div class="col-sm-1">
               <p><%= link_to "Leave", leave_path, class: "btn btn-danger" %></p>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-2">
      <h1>USERS INDEX</h1>
    </div>
  </div>
	<div class="row">
		<div class="post-index col-sm-9">
			<div class="row">
				<% @users.each do |user| %>
				<div class="col-sm-4 user_box">
					<table border="3", class="box-table3">
						<tr class="box-tr3">
							<td class="box-td-top3">
								<%= link_to user_path(user.id) do %>
								<%= attachment_image_tag user, :profile_image, :fill, 70, 70, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg", size:'75x95' %>
								<% end %>
							</td>
							<td class="box-td3a">
								<h4><%= link_to user.name, user_path(user.id) %></h4>
							</td>
						</tr>
						<tr>
							<td class="box-td3b">
								 <p>follows :　<%= link_to user.follower.count, user_follows_path(user) %></p>
                                 <p>followers : <%= link_to user.followed.count, user_followers_path(user) %></p>
                            </td>
                            <td class="box-td3c">
								<% if current_user != user %>
								<% if current_user.following?(user) %>
									<p><%= link_to 'Unfollow', user_relationships_path(user.id), method: :delete, class: "btn text-danger" %></p>
									<% else %>
									 <p><%= link_to 'Follow', user_relationships_path(user.id), method: :POST, class: "btn btn-info" %></p>
									<% end %>
									<% end %>
							</td>
						</tr>
					</table>
				</div>
				<% end %>
			</div>
		</div>
		<%= render 'users/sidebar', user:current_user %>
		<!-- サイドバー -->
	</div>
	<div class="row">
		<div class="col-sm-9 text-center">
			<%= paginate(@users) %>
		</div>
	</div>

app/views/users/leave.html.erb
<div class="container">
  <h4 class="text-center"><strong>本当に退会しますか？</strong></h4>
  <p class="withdraw-confirm-message">
         <p class="text-center">退会すると これまでの投稿が<br>
     　　　　　　閲覧できなくなります。<br>
    退会する場合は、「退会する」をクリックしてください。</p><br>
  <div class="row">
    <div class="col-xs-4"></div>
    <div class="col-xs-2"><%= link_to '退会しない', user_path(current_user.id), class: "btn btn-primary" %></div>
    <div class="col-xs-2"><%= link_to '退会する', user_path(current_user.id), method: :delete, class: "btn btn-danger" %></div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-offset-2">
			<h1>PROFILE</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-3 col-sm-offset-3">
			<h3>Follows :　<%= link_to @user.follower.count, user_follows_path(@user), class: "btn btn-default" %></h3>
			<h3>Followers : <%= link_to @user.followed.count, user_followers_path(@user), class: "btn btn-default" %></h3>
			<p> <% if current_user != @user %>
				<% if current_user.following?(@user) %>
				<%= link_to 'Unfollow', user_relationships_path(@user.id), method: :delete, class: "btn btn-outline-danger text-danger btn-lg" %>
				<% else %>
				<%= link_to 'Follow', user_relationships_path(@user.id), method: :POST, class: "btn btn-info btn-lg" %></p>
				<% end %>
			    <% end %>
			</div>
			<div class="col-sm-3">
				<%= attachment_image_tag @user, :profile_image, :fill, 200, 200, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size:'150x170' %>
			</div>
		</div>
		<div class="row">
			<div class="show-table2 col-sm-8 col-sm-offset-2">
				<table class="table">
					<tr class="show-tr2">
						<th>Your name</th>
						<td class="show-td2a"><%= @user.name %></td>
					</tr>
					<tr class="show-tr2">
						<th>Introduction</th>
						<td class="show-td2b"><%= @user.introduction %></td>
					</tr>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-offset-9">
				<% if @user == current_user %>
				<p><%= link_to "Edit", edit_user_path(@user), class: "btn btn-warning" %></p>
				<% end %>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<% if @user != current_user %>
				<% @posts.each do |post| %>
				<div class="col-sm-3 post_box">
					<table border="1", class="box-table2">
						<tr class="box-tr2">
							<td colspan="2", class="box-td-top2"><%= post.date %></td>
						</tr>
						<tr class="box-tr2">
							<td class="box-td2">
								<%= attachment_image_tag post.user, :profile_image, :fill, 70, 70, format: 'jpeg', class: "img-circle center-block profile-img", fallback: "no_image.jpg", size:'75x95' %>
							</td>
							<td class="box-td2">
								<ul>
									<li>
										<span><%= link_to post.title, post_path(post.id), class: "pull-left" %></span>
									</li>
									　　<% if post.favorited_by?(current_user) %>
									<li><%= link_to post_favorites_path(post), class: "pull-left", method: :delete do %>
										<span class="glyphicon glyphicon-heart"><%= post.favorites.count %></span>
										<% end %>
										<% else %>
										<%= link_to post_favorites_path(post), class: "pull-left", method: :post do %>
										<span class="glyphicon glyphicon-heart-empty"><%= post.favorites.count %></span>
									</li>
									<% end %>
									<% end %>
								</td>
							</tr>
						</table>
					</div>
					<% end %>
				</div>

				<% end %>
			</div>
</div>