config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followed', as: 'follows'
    get 'followers' => 'relationships#follower', as: 'followers'
    get 'leave', :on => :collection
  end

  resources :posts do
  	resource :favorites, only: [:create, :destroy]
    post "bookmarks" => 'bookmarks#create'
    delete '/bookmarks' => 'bookmarks#destroy'
  end

  root to: 'home#top'
  get 'home/about' => 'home#about'
  get 'home/index' => 'home#index'
  get 'users/leave' => 'users#leave', as: 'leave'
  get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def top
	end

	def index
	  @posts = current_user.posts.order(created_at: :desc).page(params[:page]).per(14)
	  #@posts = Post.where(user_id:current_user).page(params[:page]).per(20)
	end

	def about
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container">
    <div class="row">
       <div class="col-xs-8 col-xs-offset-2">
                <h1>About</h1>
                <h3>
                    MEDIAは、英語学習の日記をつけ、投稿、閲覧ができるサイトです。<br>
                    学習した内容を書き起こして、復習に役立ててください。<br>
                </h3>
                <div class="about-img bg-image-full" style="background-image: url('https://unsplash.it/1900/1080?image=1073');">
                    <div style="height: 300px;"></div>
                </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-offset-2">
			<h1>MY DIARIES</h1>
		</div>
	</div>
	<div class="row">
		<div class="post-index col-sm-9">
			<div class="row">
				<div class="col-sm-4 new_post">
					<span><%= link_to new_post_path, class: "btn btn-primary btn-circle new-btn" do %>
						<P class="new-btn-box">＋</P>
						<% end %>
					</span>
				</div>
				<% @posts.each do |post| %>
				<div class="col-sm-4 my_post_box">
					<table border="3", class="box-table1">
						<tr class="box-tr1">
							<td colspan="2", class="box-td-top1"><%= post.date %></td>
						</tr>
						<tr class="box-tr1">
							<td class="box-td1">
								<%= attachment_image_tag post.user, :profile_image, :fill, 70, 70, format: 'jpeg', class: "profile-img pull-left img-circle", fallback: "no_image.jpg", size:'70x90' %>
							</td>
							<td class="box-td1"><span><%= link_to post.title, post_path(post.id), class: "pull-left" %></span>
							</td>
						</tr>
					</table>
				</div>
				<% end %>
			</div>
		</div>
		<%= render 'users/sidebar', user:current_user %>
	</div>
	<div class="row">
		<div class="col-sm-9 text-center">
			<%= paginate(@posts) %>
		</div>
	</div>
</div>

app/views/home/top.html.erb
<div class="top-img bg-image-full" style="background-image: url('https://unsplash.it/1900/1080?image=1073');">
  <!-- Put anything you want here! There is just a spacer below for demo purposes! -->
  <div style="height: 300px;"></div>
</div>

<!-- Content section -->
<section class="py-5">
  <div class="container">
    <div class="row">
       <div class="col-xs-8 col-xs-offset-2">
      <h1 class="top-title"><span>M</span>y <span>E</span>nglish <span>DIA</span>ry</h1>
      <p class="lead">You can write your own diary for leaning, try to write!</p>
    </div>
    </div>
 </div>
  </section>
</div>
</div>
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
   <%= link_to "Log in", new_user_session_path, class: "btn btn-primary btn-block" %>
 </div>
</div>
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-default btn-block" %>
  </div>
</div>