config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followed', as: 'follows'
    get 'followers' => 'relationships#follower', as: 'followers'
    get 'leave', :on => :collection
  end

  resources :posts do
  	resource :favorites, only: [:create, :destroy]
    post "bookmarks" => 'bookmarks#create'
    delete '/bookmarks' => 'bookmarks#destroy'
  end

  root to: 'home#top'
  get 'home/about' => 'home#about'
  get 'home/index' => 'home#index'
  get 'users/leave' => 'users#leave', as: 'leave'
  get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'


end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user

	has_many :favorites, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	has_many :users, through: :bookmarks

	validates :date, presence: true
	validates :title, presence: true
	validates :time, presence: true
	validates :word, presence: true
	validates :body, presence: true

	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    end

    def bookmark_by?(user)
    bookmarks.where(user_id: user.id).exists?
    end

    default_scope -> { order(created_at: :desc) }
    scope :search_by_keyword, -> (keyword) {
    where("title LIKE :keyword OR word LIKE :keyword OR body LIKE :keyword", keyword: "%#{sanitize_sql_like(keyword)}%",keyword: "%#{sanitize_sql_like(keyword)}%",keyword: "%#{sanitize_sql_like(keyword)}%" ) if keyword.present?
}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!

	def index
		if signed_in?
           @post  = Post.where(user_id:current_user).build
        if params[:q]
           @posts = Post.search_by_keyword(params[:q])
                        .page(params[:page])
         else
          @posts = Post.order(created_at: :desc).page(params[:page]).per(15)
      end
      end
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			redirect_to home_index_path
		else
			render :new
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to home_index_path(@post.id)
	    else
	    	render :edit
	    end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to home_index_path
	end

	def bookmarks
    end

	private
	def post_params
	   params.require(:post).permit(:date, :title, :time, :word, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
	def time_list
    [
      ['10min', '10min'],
      ['20min', '20min'],
      ['30min', '30min'],
      ['40min', '40min'],
      ['50min', '50min'],
      ['1h', '1h'],
      ['1h 15min', '1h 15min'],
      ['1h 30min', '1h 30min'],
      ['1h 45min', '1h 45min'],
      ['2h', '2h'],
      ['2h 15min', '2h 15min'],
      ['2h 30min', '2h 30min'],
      ['2h 45min', '2h 45min'],
      ['3h', '3h'],
      ['3h 15min', '3h 15min'],
      ['3h 30min', '3h 30min'],
      ['3h 45min', '3h 45min'],
      ['4h', '4h'],
      ['4h 15min', '4h 15min'],
      ['4h 30min', '4h 30min'],
      ['4h 45min', '4h 45min'],
      ['5h', '5h'],
      ['5h 15min', '5h 15min'],
      ['5h 30min', '5h 30min'],
      ['5h 45min', '5h 45min'],
      ['more than 6h', 'more than 6h'],
    ]
  end
end

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-offset-2">
			<h1>DIARY EDIT</h1>
		</div>
	</div>
	  <%= form_for(@post, url: post_path) do |f| %>
	  <div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<% if @post.errors.any? %>
			<div id="error_explanation" class="alert alert-danger">
				<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
				<ul>
					<% @post.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="show-table1 col-sm-8 col-sm-offset-2">
			<table class="table">
						<div class="show-table1 col-sm-8 col-sm-offset-2">
			<table class="table">
				<tr class="show-tr1">
					<td>学習日</td>
					<td><%= f.date_field :date %></td>
				</tr>
				<tr class="show-tr1">
					<td>学習項目</td>
					<td><%= f.text_field :title %></td>
				</tr>
				<tr class="show-tr1">
					<td>学習時間</td>
					<td><%= f.select :time, time_list, {include_blank: "学習時間"}, :required => true %></td>
				</tr>
				<tr class="show-tr1">
					<td>新出単語</td>
					<td><%= f.text_area :word %></td>
				</tr>
				<tr>
					<td class="show-td1">学習日記</td>
					<td></td>
				</tr>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="show-table1 col-sm-6 col-sm-offset-3">
			<p class="show-body"><%= f.text_area :body %></p>
		</div>
	</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-4 col-md-offset-8">
		   <p><%= f.submit "Save", class: "btn btn-primary" %></p>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-2">
      <h1>POSTED DIARIES</h1>
    </div>
  </div>
	<div class="row">
		<div class="post-index col-sm-9 ">
			<div class="row">
				<% @posts.each do |post| %>
				<div class="col-sm-4 post_box">
					<table border="3", class="box-table2">
						<tr class="box-tr2">
							<td colspan="2", class="box-td-top2"><%= post.date %></td>
						</tr>
						<tr class="box-tr2">
							<td class="box-td2">
								<%= link_to user_path(post.user_id) do %>
								<%= attachment_image_tag post.user, :profile_image, :fill, 70, 70, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size:'70x90' %>
								<% end %>
							</td>
							<td class="box-td2">
								<ul>
									<li><%= link_to post.title, post_path(post.id), class: "pull-left" %></li>
									<li><% if post.favorited_by?(current_user) %></li>
									<li><%= link_to post_favorites_path(post), class: "pull-left", method: :delete do %>
										<p class="glyphicon glyphicon-heart"><%= post.favorites.count %></p>
										<% end %>
										<% else %>
										<%= link_to post_favorites_path(post), class: "pull-left", method: :post do %>
										<p class="glyphicon glyphicon-heart-empty"><%= post.favorites.count %></p>
									<% end %>
									<% end %>
								</li>
								</td>
							</tr>
						</table>
					</div>
					<% end %>
				</div>
			</div>
			<%= render 'users/sidebar', user:current_user %>
		</div>
		<div class="row">
			<div class="col-sm-9 text-center">
				<%= paginate(@posts) %>
			</div>
		</div>
	</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-offset-2">
			<h1>NEW POST</h1>
		</div>
	</div>
	<%= form_for(@post, url: posts_path) do |f| %>
	<div class="row">
		<div class="col-sm-3 col-sm-offset-2">
			<% if @post.errors.any? %>
			<div id="error_explanation" class="alert alert-danger">
				<h3><%= @post.errors.count %></h3>
				<ul>
					<% @post.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="show-table1 col-sm-8 col-sm-offset-2">
			<table class="table">
				<tr class="show-tr1">
					<td>学習日</td>
					<td><%= f.date_field :date %></td>
				</tr>
				<tr class="show-tr1">
					<td>学習項目</td>
					<td><%= f.text_field :title %></td>
				</tr>
				<tr class="show-tr1">
					<td>学習時間</td>
					<td><%= f.select :time, time_list, {include_blank: "学習時間"}, :required => true %></td>
				</tr>
				<tr class="show-tr1">
					<td>新出単語</td>
					<td><%= f.text_area :word %></td>
				</tr>
				<tr>
					<td class="show-td1">学習日記</td>
					<td></td>
				</tr>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="show-table1 col-sm-6 col-sm-offset-3">
			<p class="show-body"><%= f.text_area :body %></p>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-4 col-sm-offset-8">
			<p><%= f.submit 'Post', class: "btn btn-primary" %></p>
		</div>
	</div>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-offset-2">
			<h1>English Diary</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-3 col-sm-offset-2">
			<h3>　投稿者</h3>
		</div>
		<div class="col-sm-3">
			<table border="1", class="box-table5">
				<tr class="box-tr5">
					<td class="box-td-top5">
						<%= link_to user_path(@post.user_id) do %>
						<%= attachment_image_tag @post.user, :profile_image, :fill, 50, 50, format: 'jpeg', class: "img-circle center-block profile-img", fallback: "no_image.jpg", size:'60x80' %>
						<% end %>
					</td>
					<td class="box-td5">
						<h3><%= link_to @post.user.name, user_path(@post.user_id) %></h3>
					</td>
				</tr>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="show-table1 col-sm-8 col-sm-offset-2">
			<table class="table">
				<tr class="show-tr1">
					<td>学習日</td>
					<td><%= @post.date %></td>
				</tr>
				<tr class="show-tr1">
					<td>学習項目</td>
					<td><%= @post.title %></td>
				</tr>
				<tr class="show-tr1">
					<td>学習時間</td>
					<td><%= @post.time %></td>
				</tr>
				<tr class="show-tr1">
					<td>新出単語</td>
					<td><%= @post.word %></td>
				</tr>
				<tr>
					<td class="show-td1">学習日記</td>
					<td></td>
				</tr>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="show-table1 col-sm-6 col-sm-offset-3">
			<p class="show-body"><%= @post.body %></p>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-1 col-md-offset-8">
			<% if @post.favorited_by?(current_user) %>
			<%= link_to post_favorites_path(@post), method: :delete do %>
			<span class="glyphicon glyphicon-heart"><%= @post.favorites.count %></span>
			<% end %>
			<% else %>
			<%= link_to post_favorites_path(@post), method: :post do %>
			<span class="glyphicon glyphicon-heart-empty"><%= @post.favorites.count %></span>
			<% end %>
			<% end %>
		</div>
		<div class="col-sm-1">
			<% if !Bookmark.exists?(user_id: current_user.id, post_id: @post.id) %>
			<p><%= link_to "Bookmark",post_bookmarks_path(@post), class: "btn btn-success", method: :post %></p>
			<% else %>
			<p><%= link_to "Cancel",post_bookmarks_path(@post), class: "btn btn-default", method: :delete %></p>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-2 col-md-offset-7">
			　　<% if @post.user == current_user %>
			<%= link_to "Edit", edit_post_path(@post), class: "btn btn-warning pull-right" %>
		</div>
		<div class="col-sm-1">
			<%= link_to "Destroy", post_path(@post.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？"  %>
			<% end %>
		</div>
	</div>
</div>