config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followed', as: 'follows'
    get 'followers' => 'relationships#follower', as: 'followers'
    get 'leave', :on => :collection
  end

  resources :posts do
  	resource :favorites, only: [:create, :destroy]
    post "bookmarks" => 'bookmarks#create'
    delete '/bookmarks' => 'bookmarks#destroy'
  end

  root to: 'home#top'
  get 'home/about' => 'home#about'
  get 'home/index' => 'home#index'
  get 'users/leave' => 'users#leave', as: 'leave'
  get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MEDIA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-fixed-top">
            <div class="container">
              <div class="navbar-header">
                  <nav class="nav navbar-nav navbar-left">
                   <h1>MEDIA</h1>
                   </nav>
              </div>
                <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                        <li>Welcome、<%= current_user.name %>！</li>
                        <li><%= link_to ' My page', home_index_path(current_user) %></li>
                        <li><%= link_to ' Timeline', posts_path %></li>
                        <li><%= link_to ' Users', users_path %></li>
                        <li><%= link_to ' Bookmarks', bookmarks_path %></li>
                        <li><%= link_to ' Log_out', destroy_user_session_path, method: :delete %></li>
                        <div class="navbar-form navbar-right">
                          <%= form_tag(posts_path, method: :get) do %>
                          <div class="form-group">
                              <%= search_field_tag "q", params[:q], class: "form-control", placeholder: "Search" %>
                              <%= submit_tag "Search", class: "btn btn-default" %>
                          </div>
                          <% end %>
                         </div>
                    <% else %>
                        <li><%= link_to ' Home', root_path %></li>
                        <li><%= link_to ' About', home_about_path %></li>
                        <li><%= link_to ' Sign_up', new_user_registration_path %></li>
                        <li><%= link_to ' Log_in', new_user_session_path %></li>
                    <% end %>
                </ul>
            </div>
        </nav>
    <%= yield %>
  </body>
</html>